# サイト設定
title: nmin blog
subtitle: nmin blog
description: 技術メモブログ
author: n-has3
url: "https://nmin70.github.io"
baseurl: "/knowledge"

# ビルド設定
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 出力先設定
destination: ./docs

# パーマリンク設定
permalink: /:year/:month/:day/:title/

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "n-has3"

# 表示設定
show_excerpts: true
date_format: "%Y年%m月%d日"

# コレクション設定
collections:
  posts:
    output: true

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
